name: Build Fossify Keyboard (FOSS only)

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Build only fossDebug APK
        run: ./gradlew assembleFossDebug

      - name: Upload FOSS APK
        uses: actions/upload-artifact@v4
        with:
          name: FossifyKeyboard-foss-debug
          path: app/build/outputs/apk/foss/debug/app-foss-debug.apk
